AppBundle\Entity\Book:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\BookRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    year:
      type: integer
  manyToMany:
    authors:
      targetEntity: AppBundle\Entity\Author
      inversedBy: books
      joinTable:
        name: author_book
        joinColumns:
          book_id:
            referencedColumnName: id
        inverseJoinColumns:
          author_id:
            referencedColumnName: id
    categories:
      targetEntity: AppBundle\Entity\Category
      inversedBy: books
      joinTable:
        name: category_book
        joinColumns:
          book_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
  lifecycleCallbacks: {  }
